<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="/css/main.css">
</head>
<body>
    <div class="scene">
        <div class="overlay"></div>
        <div class="overlay"></div>
        <div class="overlay"></div>
        <div class="overlay"></div>
        <span class="bg-403">403</span>
        <div class="text">
            <span class="hero-text"></span>
            <span class="msg">Unauthorized <span>Access</span>:(</span>
            <span class="support">
            <span>You must be an Admin to view this site!</span>
          <a href="/">Go Home</a>
        </span>
        </div>
        <div class="lock"></div>
    </div>
</body>
</html>